### ISSUE TITLE
[startup crash] Crash on TWM-0.4 when Bobby or Slight-gui-modifications is loaded

### ISSUE THREAD

**Issue by Toilet-Man** [Osmiooo/wildmod#24] opened 2022-01-11 03:05 UTC
Title says it all but here's a short description: the game crashes on clientside startup when Bobby 3.0.1 and/or Slight-gui-modifications 2.0.2 is loaded, I'm here to help if anything.

Tell me what could cause this, I'm interested!

Bobby:
[latest.log](https://github.com/Osmiooo/wildmod/files/7843371/latest.log)

Slight-gui-modifications:
[latest.log](https://github.com/Osmiooo/wildmod/files/7843379/latest.log)

Thanks for looking into it <3

**Comment by AViewFromTheTop** [comment] 2022-01-11 13:35
It’s possible that the problem is actually with my mod Accurate Sculk (or Sculk if you got it form Modrinth,) as TWM needs to access some of the same things my mod needs to, it’s caused crashes for me. Don’t worry though, Accurate Sculk has been merged into TWM, which should become more obvious in the next update. 
Does the game still crash if you delete Accurate Sculk?

**Comment by Toilet-Man** [comment] 2022-01-13 06:36
It doesn't crash! Removing Sculk fixed it, thanks a lot <3

**Comment by AViewFromTheTop** [comment] 2022-01-13 15:00
> It doesn't crash! Removing Sculk fixed it, thanks a lot <3

No problem!

**Closed by AViewFromTheTop** 2022-01-13 15:00 UTC
