### ISSUE TITLE
Sculk shrieker stops working upon making a new world

### ISSUE THREAD

**Issue by Superwneg64** [Osmiooo/wildmod#30] opened 2022-01-14 01:25 UTC
I encountered a bug where if I summon a warden and back out and try it in another world, the heartbeat sounds won't play and the warden won't spawn.

Steps to replicate:
Recommended: turn subtitles on
Prerequisite: Experimental Beta 0.5
1: Spawn the warden with the sculk shrieker in one world
2: After the warden spawns and fully emerges, exit and create a new world or load another one up
3: Upon loading a new world, activate the sculk shrieker
Result: Warden won't spawn, nor will heartbeat sounds play
Expected Result: Warden spawns/heartbeart sounds play

Video of replication [here](https://cdn.discordapp.com/attachments/780753559725670431/931357923945361418/Minecraft__1.18.1_2022-01-13_20-18-08.mp4)

**Comment by AViewFromTheTop** [comment] 2022-01-14 01:39
By chance was the second world a superflat? If so, this should be fixed in the full release- I can't replicate it.
(I also can't watch the video, that's why I'm asking)

**Comment by Superwneg64** [comment] 2022-01-14 01:41
> By chance was the second world a superflat? If so, this should be fixed in the full release- I can't replicate it. (I also can't watch the video, that's why I'm asking)

Both worlds are normal worlds, as you can see in the video that I linked, the video is too big to be directly uploaded to github, so I uploaded it to discord and linked it instead

**Comment by AViewFromTheTop** [comment] 2022-01-14 01:43
> > By chance was the second world a superflat? If so, this should be fixed in the full release- I can't replicate it. (I also can't watch the video, that's why I'm asking)
> 
> Both worlds are normal worlds, as you can see in the video that I linked, the video is too big to be directly uploaded to github, so I uploaded it to discord and linked it instead

I was just able to replicate it, I'm pretty sure I found the cause. The fix should be easy, so expect this to get closed really soon.
Thank you for reporting this issue!

**Closed** 2022-01-14 01:47 UTC
