### ISSUE TITLE
Mod Conflict "See through lava"

### ISSUE THREAD

**Issue by KMFrench1** [Osmiooo/wildmod#130] opened 2022-02-09 15:06 UTC
The ability's to see through lava that other mods add stops working if I install this mod.

Example mod that conflicts:
https://www.curseforge.com/minecraft/mc-mods/see-through-lava-water

**Comment by MerpisMe** [comment] 2022-02-09 15:15
This is because we use overrides that sets the lava fog to default if the player doesn't have darkness. The reason we have it like that is because otherwise there would be a desync after the fog is finished pulsing. For now, I'll be marking this as won't fix as we have no viable solution.

**Comment by Soro335** [comment] 2022-02-09 15:16
Do you have any mods that change the rendering/fog in the game? If not, then perhaps this problem is caused by the darkness effect.

**Comment by MerpisMe** [comment] 2022-02-09 15:17
> Do you have any mods that change the rendering/fog in the game? If not, then perhaps this problem is caused by the darkness effect.


>> that other mods add

@Soro335

**Comment by LIUKRAST** [comment] 2022-02-09 15:26
its probably a problem related to darkness effect, since i completely overrided the rendering method. Ill try to find a better way to return a darkness effect instead of completely remove the vanilla rendering method

**Comment by LIUKRAST** [comment] 2022-02-10 20:58
i hopefully fixed this issue. From now the code will only override the vanilla rendering while theres darkness,  not in full time.

 @MerpisMe & @AViewFromTheTop also you should not put a sound effect in a rendering class, it does not do anything wrong, but its meant for rendering... well does not mean you have to change something just wanted to let you know
![image](https://user-images.githubusercontent.com/73425030/153495208-45ee9bd3-f8be-44cd-9998-c3ab574aef4c.png)

**Comment by LIUKRAST** [comment] 2022-02-10 20:58
is there a "hopefully fixed" button or something

**Comment by MerpisMe** [comment] 2022-02-10 20:59
> i hopefully fixed this issue. From now the code will only override the vanilla rendering while theres darkness, not in full time.
> 
> @MerpisMe & @AViewFromTheTop also you should not put a sound effect in a rendering class, it does not do anything wrong, but its meant for rendering... well does not mean you have to change something just wanted to let you know ![image](https://user-images.githubusercontent.com/73425030/153495208-45ee9bd3-f8be-44cd-9998-c3ab574aef4c.png)

it wouldn't work otherwise, the variables wouldn't sync between classes.

**Closed** 2022-02-15 14:50 UTC
Labels: bug, resolved, rendering, mod conflict
