### ISSUE TITLE
Mangrove Biome crashes Server/Client!

### ISSUE THREAD

**Issue by marewey** [Osmiooo/wildmod#68] opened 2022-01-26 03:33 UTC
>Description: Ticking entity

> java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
	at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
	at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
	at net.minecraft.class_1542.method_5773(class_1542.java:99)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

>A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

> -- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
	at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
	at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
	at net.minecraft.class_1542.method_5773(class_1542.java:99)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

>-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 394
	Entity Name: block.twm.mangrove_propagule
	Entity's Exact location: -774.36, 75.00, 2942.88
	Entity's Block location: World: (-775,75,2942), Section: (at 9,11,14 in -49,4,183; chunk contains blocks -784,-64,2928 to -769,319,2943), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,-64,2560 to -513,319,3071)
	Entity's Momentum: 0.00, -0.12, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by AViewFromTheTop** [comment] 2022-01-26 15:06
Duplicate of #47. I'd recommend you paste the logs there!

**Closed by AViewFromTheTop** 2022-01-26 15:06 UTC
Labels: duplicate
