### ISSUE TITLE
Ticking entity I java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by TheButterbrotMan** [Osmiooo/wildmod#120] opened 2022-02-07 18:56 UTC
Im running on fabric 0.13.1 and using version 0.5 of your mod.

https://bytebin.lucko.me/W0ikxGA1Bz

**Comment by AViewFromTheTop** [comment] 2022-02-07 19:07
Duplicate of #47, resolved in the upcoming 0.6 update.

**Closed by AViewFromTheTop** 2022-02-07 19:07 UTC
Labels: duplicate
