### ISSUE TITLE
Warden made everyone in the server lost connection.

### ISSUE THREAD

**Issue by NameIessMoment** [Osmiooo/wildmod#18] opened 2022-01-07 12:25 UTC
I was with a server with my friends and I decided to summon the warden, but then it made everyone lost connection. When I try to reconnect, it keep showing "connection lost". After 2 tried I was able to be in the server and then when I hit the warden, it just lost connection.

here the video.
https://i.gyazo.com/1a57c80f987a15108e6839c8e85c21b4.mp4

**Comment by BluePhoenixLOL** [comment] 2022-01-07 18:07
oh no

**Comment by BluePhoenixLOL** [comment] 2022-01-07 19:27
can you please show a crash report?

**Comment by Soro335** [comment] 2022-01-07 19:29
![Uploading fb51980f7d0ca9175f8e236d17d0fb3f.png…]()

**Comment by Soro335** [comment] 2022-01-07 19:33
![fb51980f7d0ca9175f8e236d17d0fb3f](https://user-images.githubusercontent.com/82042293/148597252-8befe377-5ef8-44fd-a2d5-86f6cbfdea81.png)

**Comment by AViewFromTheTop** [comment] 2022-01-07 19:45
[14:41:50] [Netty Server IO #3/ERROR] (Minecraft) Could not serialize net.minecraft.command.argument.TestFunctionArgumentType@65f79e71 (class net.minecraft.command.argument.TestFunctionArgumentType) - will not be sent to client!
[14:41:50] [Netty Server IO #3/ERROR] (Minecraft) Could not serialize net.minecraft.command.argument.TestClassArgumentType@28f93965 (class net.minecraft.command.argument.TestClassArgumentType) - will not be sent to client!
[14:41:53] [Server thread/INFO] (Minecraft) [Lunade_: Set own game mode to Creative Mode]
[14:42:16] [Netty Server IO #3/ERROR] (Minecraft) java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Identifier.toString()" because "id" is null
[14:42:16] [Server thread/INFO] (Minecraft) Lunade_ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Identifier.toString()" because "id" is null
[14:42:16] [Server thread/INFO] (Minecraft) Lunade_ left the game

wth?

**Comment by AViewFromTheTop** [comment] 2022-01-07 19:48
My assumption is that we just need more if (!world.isClient()) checks, but I have no clue.

**Comment by AViewFromTheTop** [comment] 2022-01-07 20:02
I've tested some things.
Here's what's NOT causing the issue so far:
NBT
The "listen" method
CreateVibration

**Comment by AViewFromTheTop** [comment] 2022-01-07 20:25
You don't get kicked if you're further from the Warden. Considering I haven't found the issue to be with sounds, I have no clue what's going on.

**Comment by AViewFromTheTop** [comment] 2022-01-07 20:39
I've tested everything I've changed and then some more. I genuinely have no clue what's causing this.

**Comment by AViewFromTheTop** [comment] 2022-01-09 02:37
Could this be the cause of the issue? (in SimpleGameEventDispatcherMixin)
"                                    new Identifier("wooledboots", "wooled_chainmail_boots").equals(identity) ||
                                            new Identifier("wooledboots", "wooled_gold_boots").equals(identity) ||
                                            new Identifier("wooledboots", "wooled_diamond_boots").equals(identity) ||
                                            new Identifier("wooledboots", "wooled_netherite_boots").equals(identity) ||
                                            new Identifier("wooledboots", "wooled_iron_boots").equals(identity)"
The error WAS about an Identifier not being able to be sent to the client, after all (I think)

**Comment by LIUKRAST** [comment] 2022-01-11 10:58
I think the issue comes from ClickGameEvent class

**Comment by AViewFromTheTop** [comment] 2022-01-11 14:16
> I think the issue comes from ClickGameEvent class

That's not causing the problem. The ClickGameEvent class is only used if a Sculk Sensor detects something or a mob dies (used to control Sculk Growths easier,) and that's it. I made a custom build of TWM that comments out all code relating to ClickGameEvent and removes the class itself and this problem still occurs. 
On top of that, I've been able to play with my mod on a server without an issue for quite some time- since the class is used for the same exact thing in both mods and removing it doesn't fix any problems, it simply isn't the issue.

**Comment by AViewFromTheTop** [comment] 2022-01-12 01:18
I was thinking about this issue again, so I tested with all Sculk blocks nothing happens.
Warden emerging? Nothing. Then I attacked the warden while flying, nothing.
The moment I touch the ground, BOOM.
The issue is probably with GameEventDispatcher, probably has to do with GameEvents as a whole. It isn't ClickGameEvent specifically (I'd removed it while testing,) but probably just GameEvents in general. If not, then vibrations- although I'm 99% sure removing those didn't change a thing.

**Comment by AViewFromTheTop** [comment] 2022-01-12 15:22
> I was with a server with my friends and I decided to summon the warden, but then it made everyone lost connection. When I try to reconnect, it keep showing "connection lost". After 2 tried I was able to be in the server and then when I hit the warden, it just lost connection.
> 
> here the video. https://i.gyazo.com/1a57c80f987a15108e6839c8e85c21b4.mp4

Should be fixed in the next update.
The source of this was the PositionSource class, which is used to determine where a vibration should move to. Minecraft handles this in a bit of a strange way on the client, and you need to use either BlockPositionSource or EntityPositionSource for it to work, although EntityPositionSource is a bit broken.
TL,DR: PositionSources are a little broken client-side

**Comment by BluePhoenixLOL** [comment] 2022-01-13 17:58
Fixed in 0.5 Release Candidate. Download on our discord: https://discord.gg/3Af3Uer2Hj

**Closed by BluePhoenixLOL** 2022-01-13 17:58 UTC
